apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: node:20-alpine
          command: ["npm", "run", "dev"]
          env:
            - name: NODE_ENV
              value: "dev"
            - name: MONGO_USERNAME
              value: "admin"
            - name: MONGO_PASSWORD
              value: "password"
            - name: MONGO_HOSTNAME
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: "satoro_bot"
            - name: REDIS_PASSWORD
              value: "password"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: RABBITMQ_PORT
              value: "5672"
            - name: DOTA_API_PORT
              value: "stratz"
          volumeMounts:
            - name: app-volume
              mountPath: /usr/app
            - name: node-modules
              mountPath: /usr/app/node_modules
      volumes:
        - name: app-volume
          hostPath:
            path: /usr/app
        - name: node-modules
          hostPath:
            path: /usr/app/node_modules

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbit-mq  # Указывает на ваш сервис RabbitMQ в Kubernetes
  ports:
    - protocol: TCP
      port: 5672   # Порт RabbitMQ
      targetPort: 5672
