apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  stratzApiToken: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SlRkV0pxWldOMElqb2lZemxrTkRnMU9USXRNRFZoWWkwME5HSTNMV0ptTXprdE5qazRObU15TVRjeU1XTm1JaXdpVTNSbFlXMUpaQ0k2SWpnM05qUTNORGszTUNJc0ltNWlaaUk2TVRjeE1ESTBNemswT0N3aVpYaHdJam94TnpReE56YzVPVFE0TENKcFlYUWlPakUzTVRBeU5ETTVORGdzSW1semN5STZJbWgwZEhCek9pOHZZWEJwTG5OMGNtRjBlaTVqYjIwaWZRLkYwa3p6em1MRXFyNXZIcWtpRVluQkNHQlZmR3VuekJaVUgySUVZX0NMYlU=
